// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StateNationalParks.Models;

namespace StateNationalParks.Migrations
{
    [DbContext(typeof(StateNationalParksContext))]
    [Migration("20200822001843_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StateNationalParks.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            NationalParkId = 3,
                            Address = "Washington 98267",
                            Name = "North Cascade National Park"
                        },
                        new
                        {
                            NationalParkId = 4,
                            Address = "Oregon 97604",
                            Name = "Crater Lake National Park"
                        },
                        new
                        {
                            NationalParkId = 5,
                            Address = "Montana 59936",
                            Name = "Glacire National Park"
                        },
                        new
                        {
                            NationalParkId = 6,
                            Address = "California 95389",
                            Name = "Yosemite National Park"
                        },
                        new
                        {
                            NationalParkId = 7,
                            Address = "Wyoming 82190",
                            Name = "Yellowstone National Park"
                        });
                });

            modelBuilder.Entity("StateNationalParks.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(300);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 3,
                            Address = "Washington 98624",
                            Name = "Cape Disappointment State Park"
                        },
                        new
                        {
                            StateParkId = 4,
                            Address = "Oregon 97385",
                            Name = "Silver Falls State Park"
                        },
                        new
                        {
                            StateParkId = 6,
                            Address = "California 93520",
                            Name = "Pfeiffer Big Sur State Park"
                        });
                });

            modelBuilder.Entity("StateNationalParks.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
